sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250101'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250102'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250103'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250106'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250107'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250108'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250109'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250110'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250113'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250114'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250115'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250116'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250117'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250120'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250121'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250122'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250123'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250124'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250127'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250128'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250129'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250130'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250131'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250203'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250204'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250205'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250206'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250207'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250210'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250211'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250212'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250213'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250214'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250217'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250218'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250219'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250220'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250221'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250224'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250225'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250226'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250227'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250228'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250303'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250304'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250305'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250306'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250307'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250310'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250311'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250312'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250313'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250314'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250317'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250318'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250319'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250320'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250321'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250324'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250325'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250326'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250327'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250328'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250331'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250401'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250402'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250403'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250404'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250407'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250408'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250409'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250410'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250411'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250414'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250415'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250416'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250417'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250418'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250421'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250422'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250423'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250424'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250425'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250428'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250429'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250430'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250501'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250502'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250505'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250506'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250507'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250508'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250509'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250512'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250513'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250514'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250515'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250516'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250519'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250520'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250521'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250522'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250523'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250526'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250527'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250528'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250529'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250530'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250602'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250603'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250604'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250605'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250606'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250609'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250610'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250611'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250612'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250613'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250616'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250617'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20250618'" -S DORT-DB-1 -b -h-1