sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240102'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240103'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240104'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240105'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240108'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240109'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240110'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240111'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240112'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240115'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240116'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240117'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240118'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240119'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240122'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240123'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240124'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240125'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240126'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240129'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240130'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240131'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240201'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240202'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240205'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240206'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240207'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240208'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240209'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240212'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240213'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240214'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240215'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240216'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240219'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240220'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240221'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240222'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240223'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240226'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240227'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240228'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240229'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240301'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240304'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240305'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240306'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240307'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240308'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240311'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240312'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240313'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240314'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240315'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240318'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240319'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240320'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240321'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240322'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240325'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240326'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240327'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240328'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240329'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240401'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240402'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240403'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240404'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240405'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240408'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240409'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240410'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240411'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240412'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240415'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240416'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240417'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240418'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240419'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240422'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240423'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240424'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240425'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240426'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240429'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240430'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240501'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240502'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240503'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240506'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240507'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240508'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240509'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240510'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240513'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240514'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240515'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240516'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240517'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240520'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240521'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240522'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240523'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240524'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240527'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240528'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240529'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240530'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240531'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240603'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240604'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240605'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240606'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240607'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240610'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240611'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240612'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240613'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240614'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240617'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240618'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240619'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240620'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240621'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240624'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240625'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240626'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240627'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240628'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240701'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240702'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240703'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240704'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240705'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240708'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240709'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240710'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240711'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240712'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240715'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240716'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240717'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240718'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240719'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240722'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240723'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240724'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240725'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240726'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240729'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240730'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240731'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240801'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240802'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240805'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240806'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240807'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240808'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240809'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240812'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240813'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240814'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240815'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240816'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240819'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240820'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240821'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240822'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240823'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240826'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240827'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240828'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240829'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240830'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240902'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240903'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240904'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240905'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240906'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240909'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240910'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240911'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240912'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240913'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240916'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240917'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240918'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240919'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240920'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240923'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240924'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240925'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240926'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240927'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20240930'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20241001'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20241002'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20241003'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20241004'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20241007'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20241008'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20241009'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20241010'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20241011'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20241014'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20241015'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20241016'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20241017'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20241018'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20241021'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20241022'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20241023'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20241024'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20241025'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20241028'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20241029'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20241030'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20241031'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20241101'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20241104'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20241105'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20241106'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20241107'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20241108'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20241111'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20241112'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20241113'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20241114'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20241115'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20241118'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20241119'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20241120'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20241121'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20241122'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20241125'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20241126'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20241127'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20241128'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20241129'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20241202'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20241203'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20241204'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20241205'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20241206'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20241209'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20241210'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20241211'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20241212'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20241213'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20241216'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20241217'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20241218'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20241219'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20241220'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20241223'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20241224'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20241225'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20241226'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20241227'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20241230'" -S DORT-DB-1 -b -h-1
sqlcmd -E -Q"EXEC [GMIDATA].[dbo].[PROC_Load_Commission_Fees_Volume_History_2] '20241231'" -S DORT-DB-1 -b -h-1