USE [GMIDATA]
GO

DROP PROCEDURE [dbo].[PROC_Load_GNACMFF1_File_Current]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[PROC_Load_GNACMFF1_File_Current]

AS

SET NOCOUNT ON

PRINT '************************************************************************************************************'
PRINT ' [dbo].[PROC_Load_GNACMFF1_File_Current] STARTED'
PRINT '************************************************************************************************************'
SELECT GETDATE() "Start Time"

PRINT '**************************************************************************'
PRINT ' TRUNCATE TABLE [dbo].[GNACMFF1_File_Current]'
PRINT '**************************************************************************'
TRUNCATE TABLE [dbo].[GNACMFF1_File_Current]

PRINT '**************************************************************************'
PRINT ' Load [dbo].[GNACMFF1_File_Current]'
PRINT ' with [dbo].[GNACMFF1_File_Raw]'
PRINT '**************************************************************************'

SELECT GETDATE() "Start Time"

INSERT INTO [dbo].[GNACMFF1_File_Current]
(YRECID,
YFIRM,
YOFFIC,
YACCT,
YRR,
YCLASS,
YSUBCL,
YSNAME,
YTAXID,
YTAXFM,
YTAXPC,
YTAXWH,
YTAXWR,
YTAXDC,
YTAXDR,
YTAXIC,
YTAXIR,
YTAXTC,
YNOBO,
YDTCCH,
YRELMD,
YADSTL,
YCITYL,
YMAILG,
YPSTCD,
YPSTSF,
YSTAC3,
YCNTRY,
YCURCD,
YCURAC,
YATYAC,
YCPCOD,
YCVRID,
YBCNVP,
YCVCAS,
YFASRC,
YSCMNA,
YCOLMA,
YAUCOL,
YMPGMN,
YINACT,
YBLNK,
YNA1,
YNA2,
YNA3,
YNA4,
YNA5,
YNA6,
YNA7,
YOMNBS,
YOMNBF,
YOITYP,
YHTRTF,
YHTRTO,
YCMREC,
YHEDGE,
YSSECF,
YNFACD,
YDSCCD,
YFPLCD,
YSPLCD,
YFFIFO,
YSFIFO,
YCNTRA,
YFCNTR,
YWOWND,
YSCONF,
YFCONF,
YFMEMO,
YSMEMO,
YLIFCL,
YFBBIL,
YOCOFF,
YFMTAB,
YFMPCT,
YFMCAL,
YTCNF1,
YTCNF2,
YMRQCD,
YCHGMC,
YLEGAL,
YOCC1,
YOCC2,
YCOMOF,
YCOMAC,
YMGROF,
YMGRRR,
YGLGRP,
YFMLIM,
YFMMUL,
YPLLAM,
YPLLML,
YCSHIM,
YVARMG,
YMEQPC,
YFCLIM,
YFCMUL,
YPSLMT,
YADGPC,
YGPCD,
YGRMGI,
YMSTRF,
YRSKC1,
YRSKC2,
YPLDET,
YPLSUM,
YPLFYR,
YPLCST,
YSKFEE,
YBIRTH,
YREL1F,
YREL1O,
YREL1A,
YREL1T,
YREL2F,
YREL2O,
YREL2A,
YREL2T,
YCFTOF,
YCFTAC,
YCFTSB,
YCFTF2,
YCFTO2,
YCFTA2,
YCFTS2,
YEXCOF,
YEXCAC,
YEXCSB,
YEXCF2,
YEXCO2,
YEXCA2,
YEXCS2,
YGRPFM,
YGRPOF,
YGRPAC,
YGRPRR,
YREFOF,
YREFRR,
YCBTOS,
YCBTOA,
YVIOOF,
YVIOAC,
YCOLFN,
YCOLOF,
YCOLAC,
YORGNM,
YPREXC,
YMISC1,
YMISC2,
YMISC3,
YMISC4,
YMISC5,
YMISC6,
YMISC7,
YMISC8,
YMISC9,
YMISC0,
YBUYIN,
YSELIN,
YFINID,
YFINAG,
YDVDSP,
YPFOLO,
YSORDR,
YSMODT,
YFXROL,
YEXEAF,
YOPTAG,
YSIGNC,
YNEOAG,
YIDXOP,
YTRM01,
YTRM02,
YTRM03,
YTRM04,
YTRM05,
YTRM06,
YTRM07,
YTRM08,
YTRM09,
YTRM10,
YUSER,
YOPNDT,
YUPDDT,
YCHGDT,
YDLACT,
YDLAC7,
YBNRY1,
YBNRY2,
YBNRY3,
YBNRY4,
YBNRY5,
YBNRYI,
YBNRYR,
YGSFE1,
YGSFE2,
YGSFE3,
YGSFE4,
YGSFE5,
YGSFE6,
YGSFE7,
YGSFE8,
YALOCT,
YQIBST,
YCMMCL,
YSIPC,
YSFDEL,
YFAVGP,
YJPOCC,
YXTRA7,
YXTRA8,
YXTRA9,
YBLK20,
YCLCAT,
YMCRUL,
YEBKRP,
YTOPRP,
YHKERP,
YHKALW,
YBENID,
YHKOMN,
YMKLIC,
YLFIRM,
YLOFFC,
YLACCT,
YSUBAC,
YGPOFC,
YGPACC,
YGPOFF,
YGPACF,
YALMTH,
YTXMTH,
YCLRFO,
YSEGMG,
YBENOF)
SELECT --TOP 10000
CONVERT(VARCHAR(1),REPLACE(YRECID,'"','')), --YRECID
CONVERT(VARCHAR(1),YFIRM), --YFIRM
CONVERT(VARCHAR(3),YOFFIC), --YOFFIC
CONVERT(VARCHAR(5),YACCT), --YACCT
CONVERT(VARCHAR(5),YRR), --YRR
CONVERT(VARCHAR(1),YCLASS), --YCLASS
CONVERT(VARCHAR(1),YSUBCL), --YSUBCL
CONVERT(VARCHAR(20),YSNAME), --YSNAME
CONVERT(VARCHAR(15),YTAXID), --YTAXID
CONVERT(VARCHAR(1),YTAXFM), --YTAXFM
CONVERT(VARCHAR(1),YTAXPC), --YTAXPC
CONVERT(VARCHAR(1),YTAXWH), --YTAXWH
CONVERT(NUMERIC(5,5),YTAXWR), --YTAXWR
CONVERT(VARCHAR(2),YTAXDC), --YTAXDC
CONVERT(NUMERIC(5,5),YTAXDR), --YTAXDR
CONVERT(VARCHAR(2),YTAXIC), --YTAXIC
CONVERT(NUMERIC(5,5),YTAXIR), --YTAXIR
CONVERT(VARCHAR(2),YTAXTC), --YTAXTC
CONVERT(VARCHAR(1),YNOBO), --YNOBO
CONVERT(VARCHAR(1),YDTCCH), --YDTCCH
CONVERT(VARCHAR(1),YRELMD), --YRELMD
CONVERT(VARCHAR(1),YADSTL), --YADSTL
CONVERT(VARCHAR(1),YCITYL), --YCITYL
CONVERT(VARCHAR(1),YMAILG), --YMAILG
CONVERT(VARCHAR(9),YPSTCD), --YPSTCD
CONVERT(VARCHAR(2),YPSTSF), --YPSTSF
CONVERT(VARCHAR(3),YSTAC3), --YSTAC3
CONVERT(VARCHAR(2),YCNTRY), --YCNTRY
CONVERT(VARCHAR(2),YCURCD), --YCURCD
CONVERT(VARCHAR(3),YCURAC), --YCURAC
CONVERT(VARCHAR(2),YATYAC), --YATYAC
CONVERT(VARCHAR(1),YCPCOD), --YCPCOD
CONVERT(VARCHAR(1),YCVRID), --YCVRID
CONVERT(VARCHAR(2),YBCNVP), --YBCNVP
CONVERT(VARCHAR(1),YCVCAS), --YCVCAS
CONVERT(VARCHAR(1),YFASRC), --YFASRC
CONVERT(VARCHAR(1),YSCMNA), --YSCMNA
CONVERT(VARCHAR(1),YCOLMA), --YCOLMA
CONVERT(VARCHAR(1),YAUCOL), --YAUCOL
CONVERT(VARCHAR(2),YMPGMN), --YMPGMN
CONVERT(VARCHAR(1),YINACT), --YINACT
CONVERT(VARCHAR(1),YBLNK), --YBLNK
CONVERT(VARCHAR(32),YNA1), --YNA1
CONVERT(VARCHAR(32),YNA2), --YNA2
CONVERT(VARCHAR(32),YNA3), --YNA3
CONVERT(VARCHAR(32),YNA4), --YNA4
CONVERT(VARCHAR(32),YNA5), --YNA5
CONVERT(VARCHAR(32),YNA6), --YNA6
CONVERT(VARCHAR(32),YNA7), --YNA7
CONVERT(VARCHAR(1),YOMNBS), --YOMNBS
CONVERT(VARCHAR(1),YOMNBF), --YOMNBF
CONVERT(VARCHAR(1),YOITYP), --YOITYP
CONVERT(VARCHAR(1),YHTRTF), --YHTRTF
CONVERT(VARCHAR(1),YHTRTO), --YHTRTO
CONVERT(VARCHAR(1),YCMREC), --YCMREC
CONVERT(VARCHAR(1),YHEDGE), --YHEDGE
CONVERT(VARCHAR(1),YSSECF), --YSSECF
CONVERT(VARCHAR(1),YNFACD), --YNFACD
CONVERT(VARCHAR(1),YDSCCD), --YDSCCD
CONVERT(VARCHAR(1),YFPLCD), --YFPLCD
CONVERT(VARCHAR(1),YSPLCD), --YSPLCD
CONVERT(VARCHAR(1),YFFIFO), --YFFIFO
CONVERT(VARCHAR(1),YSFIFO), --YSFIFO
CONVERT(VARCHAR(1),YCNTRA), --YCNTRA
CONVERT(VARCHAR(1),YFCNTR), --YFCNTR
CONVERT(VARCHAR(1),YWOWND), --YWOWND
CONVERT(VARCHAR(1),YSCONF), --YSCONF
CONVERT(VARCHAR(1),YFCONF), --YFCONF
CONVERT(VARCHAR(1),YFMEMO), --YFMEMO
CONVERT(VARCHAR(1),YSMEMO), --YSMEMO
CONVERT(VARCHAR(1),YLIFCL), --YLIFCL
CONVERT(VARCHAR(1),YFBBIL), --YFBBIL
CONVERT(VARCHAR(1),YOCOFF), --YOCOFF
CONVERT(VARCHAR(1),YFMTAB), --YFMTAB
CONVERT(NUMERIC(3,2),YFMPCT), --YFMPCT
CONVERT(VARCHAR(1),YFMCAL), --YFMCAL
CONVERT(VARCHAR(1),YTCNF1), --YTCNF1
CONVERT(VARCHAR(1),YTCNF2), --YTCNF2
CONVERT(VARCHAR(1),YMRQCD), --YMRQCD
CONVERT(VARCHAR(1),YCHGMC), --YCHGMC
CONVERT(VARCHAR(5),YLEGAL), --YLEGAL
CONVERT(VARCHAR(3),YOCC1), --YOCC1
CONVERT(VARCHAR(3),YOCC2), --YOCC2
CONVERT(VARCHAR(3),YCOMOF), --YCOMOF
CONVERT(VARCHAR(5),YCOMAC), --YCOMAC
CONVERT(VARCHAR(3),YMGROF), --YMGROF
CONVERT(VARCHAR(5),YMGRRR), --YMGRRR
CONVERT(VARCHAR(2),YGLGRP), --YGLGRP
CONVERT(VARCHAR(3),YFMLIM), --YFMLIM
CONVERT(VARCHAR(1),YFMMUL), --YFMMUL
CONVERT(VARCHAR(3),YPLLAM), --YPLLAM
CONVERT(VARCHAR(1),YPLLML), --YPLLML
CONVERT(VARCHAR(1),YCSHIM), --YCSHIM
CONVERT(VARCHAR(1),YVARMG), --YVARMG
CONVERT(NUMERIC(2,2),YMEQPC), --YMEQPC
CONVERT(VARCHAR(3),YFCLIM), --YFCLIM
CONVERT(VARCHAR(1),YFCMUL), --YFCMUL
CONVERT(VARCHAR(1),YPSLMT), --YPSLMT
CONVERT(VARCHAR(1),YADGPC), --YADGPC
CONVERT(VARCHAR(6),YGPCD), --YGPCD
CONVERT(VARCHAR(1),YGRMGI), --YGRMGI
CONVERT(VARCHAR(1),YMSTRF), --YMSTRF
CONVERT(VARCHAR(40),YRSKC1), --YRSKC1
CONVERT(VARCHAR(40),YRSKC2), --YRSKC2
CONVERT(VARCHAR(1),YPLDET), --YPLDET
CONVERT(VARCHAR(1),YPLSUM), --YPLSUM
CONVERT(VARCHAR(2),YPLFYR), --YPLFYR
CONVERT(VARCHAR(1),YPLCST), --YPLCST
CONVERT(VARCHAR(2),YSKFEE), --YSKFEE
CONVERT(NUMERIC(9,0),YBIRTH), --YBIRTH
CONVERT(VARCHAR(1),YREL1F), --YREL1F
CONVERT(VARCHAR(3),YREL1O), --YREL1O
CONVERT(VARCHAR(5),YREL1A), --YREL1A
CONVERT(VARCHAR(1),YREL1T), --YREL1T
CONVERT(VARCHAR(1),YREL2F), --YREL2F
CONVERT(VARCHAR(3),YREL2O), --YREL2O
CONVERT(VARCHAR(5),YREL2A), --YREL2A
CONVERT(VARCHAR(1),YREL2T), --YREL2T
CONVERT(VARCHAR(3),YCFTOF), --YCFTOF
CONVERT(VARCHAR(5),YCFTAC), --YCFTAC
CONVERT(VARCHAR(1),YCFTSB), --YCFTSB
CONVERT(VARCHAR(1),YCFTF2), --YCFTF2
CONVERT(VARCHAR(3),YCFTO2), --YCFTO2
CONVERT(VARCHAR(5),YCFTA2), --YCFTA2
CONVERT(VARCHAR(1),YCFTS2), --YCFTS2
CONVERT(VARCHAR(3),YEXCOF), --YEXCOF
CONVERT(VARCHAR(5),YEXCAC), --YEXCAC
CONVERT(VARCHAR(1),YEXCSB), --YEXCSB
CONVERT(VARCHAR(1),YEXCF2), --YEXCF2
CONVERT(VARCHAR(3),YEXCO2), --YEXCO2
CONVERT(VARCHAR(5),YEXCA2), --YEXCA2
CONVERT(VARCHAR(1),YEXCS2), --YEXCS2
CONVERT(VARCHAR(1),YGRPFM), --YGRPFM
CONVERT(VARCHAR(3),YGRPOF), --YGRPOF
CONVERT(VARCHAR(5),YGRPAC), --YGRPAC
CONVERT(VARCHAR(5),YGRPRR), --YGRPRR
CONVERT(VARCHAR(3),YREFOF), --YREFOF
CONVERT(VARCHAR(5),YREFRR), --YREFRR
CONVERT(VARCHAR(3),YCBTOS), --YCBTOS
CONVERT(VARCHAR(5),YCBTOA), --YCBTOA
CONVERT(VARCHAR(3),YVIOOF), --YVIOOF
CONVERT(VARCHAR(5),YVIOAC), --YVIOAC
CONVERT(VARCHAR(1),YCOLFN), --YCOLFN
CONVERT(VARCHAR(3),YCOLOF), --YCOLOF
CONVERT(VARCHAR(5),YCOLAC), --YCOLAC
CONVERT(VARCHAR(40),YORGNM), --YORGNM
CONVERT(VARCHAR(4),YPREXC), --YPREXC
CONVERT(VARCHAR(1),YMISC1), --YMISC1
CONVERT(VARCHAR(1),YMISC2), --YMISC2
CONVERT(VARCHAR(1),YMISC3), --YMISC3
CONVERT(VARCHAR(1),YMISC4), --YMISC4
CONVERT(VARCHAR(1),YMISC5), --YMISC5
CONVERT(VARCHAR(1),YMISC6), --YMISC6
CONVERT(VARCHAR(1),YMISC7), --YMISC7
CONVERT(VARCHAR(1),YMISC8), --YMISC8
CONVERT(VARCHAR(1),YMISC9), --YMISC9
CONVERT(VARCHAR(1),YMISC0), --YMISC0
CONVERT(VARCHAR(2),YBUYIN), --YBUYIN
CONVERT(VARCHAR(2),YSELIN), --YSELIN
CONVERT(VARCHAR(8),YFINID), --YFINID
CONVERT(VARCHAR(8),YFINAG), --YFINAG
CONVERT(VARCHAR(1),YDVDSP), --YDVDSP
CONVERT(VARCHAR(1),YPFOLO), --YPFOLO
CONVERT(VARCHAR(1),YSORDR), --YSORDR
CONVERT(VARCHAR(1),YSMODT), --YSMODT
CONVERT(VARCHAR(1),YFXROL), --YFXROL
CONVERT(VARCHAR(1),YEXEAF), --YEXEAF
CONVERT(VARCHAR(1),YOPTAG), --YOPTAG
CONVERT(VARCHAR(1),YSIGNC), --YSIGNC
CONVERT(VARCHAR(1),YNEOAG), --YNEOAG
CONVERT(VARCHAR(1),YIDXOP), --YIDXOP
CONVERT(VARCHAR(4),YTRM01), --YTRM01
CONVERT(VARCHAR(4),YTRM02), --YTRM02
CONVERT(VARCHAR(4),YTRM03), --YTRM03
CONVERT(VARCHAR(4),YTRM04), --YTRM04
CONVERT(VARCHAR(4),YTRM05), --YTRM05
CONVERT(VARCHAR(4),YTRM06), --YTRM06
CONVERT(VARCHAR(4),YTRM07), --YTRM07
CONVERT(VARCHAR(4),YTRM08), --YTRM08
CONVERT(VARCHAR(4),YTRM09), --YTRM09
CONVERT(VARCHAR(4),YTRM10), --YTRM10
CONVERT(VARCHAR(10),YUSER), --YUSER
CONVERT(NUMERIC(9,0),YOPNDT), --YOPNDT
CONVERT(NUMERIC(9,0),YUPDDT), --YUPDDT
CONVERT(NUMERIC(9,0),YCHGDT), --YCHGDT
CONVERT(NUMERIC(9,0),YDLACT), --YDLACT
CONVERT(NUMERIC(7,0),YDLAC7), --YDLAC7
CONVERT(VARCHAR(1),YBNRY1), --YBNRY1
CONVERT(VARCHAR(1),YBNRY2), --YBNRY2
CONVERT(VARCHAR(1),YBNRY3), --YBNRY3
CONVERT(VARCHAR(1),YBNRY4), --YBNRY4
CONVERT(VARCHAR(1),YBNRY5), --YBNRY5
CONVERT(VARCHAR(1),YBNRYI), --YBNRYI
CONVERT(VARCHAR(1),YBNRYR), --YBNRYR
CONVERT(VARCHAR(2),YGSFE1), --YGSFE1
CONVERT(VARCHAR(2),YGSFE2), --YGSFE2
CONVERT(VARCHAR(2),YGSFE3), --YGSFE3
CONVERT(VARCHAR(2),YGSFE4), --YGSFE4
CONVERT(VARCHAR(2),YGSFE5), --YGSFE5
CONVERT(VARCHAR(2),YGSFE6), --YGSFE6
CONVERT(VARCHAR(2),YGSFE7), --YGSFE7
CONVERT(VARCHAR(2),YGSFE8), --YGSFE8
CONVERT(VARCHAR(1),YALOCT), --YALOCT
CONVERT(VARCHAR(1),YQIBST), --YQIBST
CONVERT(VARCHAR(1),YCMMCL), --YCMMCL
CONVERT(VARCHAR(1),YSIPC), --YSIPC
CONVERT(VARCHAR(1),YSFDEL), --YSFDEL
CONVERT(VARCHAR(1),YFAVGP), --YFAVGP
CONVERT(VARCHAR(1),YJPOCC), --YJPOCC
CONVERT(VARCHAR(1),YXTRA7), --YXTRA7
CONVERT(VARCHAR(1),YXTRA8), --YXTRA8
CONVERT(VARCHAR(1),YXTRA9), --YXTRA9
CONVERT(VARCHAR(20),YBLK20), --YBLK20
CONVERT(VARCHAR(1),YCLCAT), --YCLCAT
CONVERT(VARCHAR(1),YMCRUL), --YMCRUL
CONVERT(VARCHAR(1),YEBKRP), --YEBKRP
CONVERT(VARCHAR(1),YTOPRP), --YTOPRP
CONVERT(VARCHAR(1),YHKERP), --YHKERP
CONVERT(VARCHAR(1),YHKALW), --YHKALW
CONVERT(VARCHAR(5),YBENID), --YBENID
CONVERT(VARCHAR(1),YHKOMN), --YHKOMN
CONVERT(VARCHAR(1),YMKLIC), --YMKLIC
CONVERT(VARCHAR(1),YLFIRM), --YLFIRM
CONVERT(VARCHAR(3),YLOFFC), --YLOFFC
CONVERT(VARCHAR(5),YLACCT), --YLACCT
CONVERT(VARCHAR(1),YSUBAC), --YSUBAC
CONVERT(VARCHAR(3),YGPOFC), --YGPOFC
CONVERT(VARCHAR(5),YGPACC), --YGPACC
CONVERT(VARCHAR(3),YGPOFF), --YGPOFF
CONVERT(VARCHAR(5),YGPACF), --YGPACF
CONVERT(VARCHAR(1),YALMTH), --YALMTH
CONVERT(VARCHAR(1),YTXMTH), --YTXMTH
CONVERT(VARCHAR(3),YCLRFO), --YCLRFO
CONVERT(VARCHAR(1),YSEGMG), --YSEGMG
CONVERT(VARCHAR(3),YBENOF) --YBENOF
FROM [dbo].[GNACMFF1_File_Raw]

SELECT @@ROWCOUNT "Records Loaded"

SELECT GETDATE() "End Time"

PRINT '************************************************************************************************************'
PRINT ' [dbo].[PROC_Load_GNACMFF1_File_Current] ENDED'
PRINT '************************************************************************************************************'
SELECT GETDATE() "End Time"

SET NOCOUNT OFF

GO