USE [GMIDATA]
GO

DROP PROCEDURE [dbo].[PROC_Load_GMIPOSF1_File_Current]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[PROC_Load_GMIPOSF1_File_Current]

AS

SET NOCOUNT ON

PRINT '************************************************************************************************************'
PRINT ' [dbo].[PROC_Load_GMIPOSF1_File_Current] STARTED'
PRINT '************************************************************************************************************'
SELECT GETDATE() "Start Time"

PRINT '**************************************************************************'
PRINT ' TRUNCATE TABLE [dbo].[GMIPOSF1_File_Current]'
PRINT '**************************************************************************'
TRUNCATE TABLE [dbo].[GMIPOSF1_File_Current]

PRINT '**************************************************************************'
PRINT ' Load [dbo].[GMIPOSF1_File_Current]'
PRINT ' with [dbo].[GMIPOSF1_File_Raw]'
PRINT '**************************************************************************'

SELECT GETDATE() "Start Time"

INSERT INTO [dbo].[GMIPOSF1_File_Current]
(PRECID,
PFIRM,
POFFIC,
PACCT,
PATYPE,
PCUSIP,
PCUSP2,
PCTYM,
PSBCUS,
PSTYPE,
PSUBTY,
PSTYP2,
PSTRIK,
PEXPDT,
PSUBAC,
PDEAL,
PTDATE,
PTPRIC,
PBS,
PLOC,
PBROKR,
PSPRED,
PTRACE,
PICODE,
PREFNO,
PSWAC1,
PSWAP1,
PSWAS1,
PSWAC2,
PSWAP2,
PSWAS2,
PZONE,
PACNTY,
PCLASS,
PSUBCL,
PRR,
PRISKG,
PMEMBR,
PSNAME,
PSRCAC,
PREFOF,
PREFRR,
POFFFN,
POFFOF,
POFFAC,
POFFAT,
PMPGMN,
PSTATA,
PSTATB,
PSTATC,
PSTATD,
PSTATE,
PSTATF,
PSTATG,
PSTATH,
PSTATJ,
PSTATK,
PSTAT1,
PSTAT2,
PSTAT3,
PSTAT4,
PSTAT5,
PSTAT6,
PSTAT7,
PSTAT8,
PSTAT9,
PQTEDT,
PQTY,
PPRTQ,
PBUSTQ,
PMAKEQ,
PLEAVQ,
PSEGQ,
PTFRQ,
PDLVYQ,
PDLVYA,
PSDSC#,
PSDSC1,
PSDSC2,
PSDSC3,
PTDSC#,
PTDSC1,
PTDSC2,
PTDSC3,
PMKVAL,
PYSTMV,
PMULTF,
PSDATE,
PEXRAT,
PRXDAT,
PIAD,
PYIELD,
PDCTCO,
PDELTA,
PLTDAT,
PCTLNO,
PPCNTY,
PEXCH,
PFC,
PTYPE,
PSYMBL,
PPTYPE,
PSUBEX,
PTRDEX,
PMATDT,
PPRTPR,
PBASIS,
PCLOSE,
PPRCDT,
PPRTCP,
PUNDCP,
PPRTUC,
PPRVCP,
PTRPRC,
PEXPR,
PPRICE,
PSPEDT,
PTPEDT,
PCURSY,
PCURCD,
PCALC,
PCMNT1,
PCMNT2,
PCMNT3,
PLEGND,
POMNCD,
PRTHT,
PSCHDL,
POC,
PCOD,
PUCUSP,
PCVTBL,
PEXBKR,
POPBKR,
POPFRM,
PGIVIO,
PGIVF#,
PIEXNG,
PIEFRM,
PCARD,
PORDER,
PCHIT,
PFEECL,
PFEEEX,
PCTI,
PORDTY,
PORDOR,
PTIME,
PTBKT,
PSESSN,
PSTINS,
PTTYPE,
PBARG1,
PBARG2,
PBARG3,
PBARG4,
PBARG5,
PMTABL,
PMINIT,
PMVARN,
PMUNTL,
PMGNCV,
PREL1F,
PREL1O,
PREL1A,
PREL1T,
PREL2F,
PREL2O,
PREL2A,
PREL2T,
PREL3F,
PREL3O,
PREL3A,
PREL3T,
PCOMM,
PFEE1,
PFEE2,
PFEE3,
PFEE4,
PFEE5,
PFEE6,
PFEE7,
PFEE8,
PFEE9,
PGICHG,
PBKCHG,
POTHER,
PGROSS,
PNET,
PMBKOF,
PMFLOR,
PMORDR,
PMWIRE,
PMOTHR,
PATCOM,
PATFE1,
PATFE2,
PATFE3,
PATFE4,
PATFE5,
PATFE6,
PATFE7,
PATFE8,
PATFE9,
PATGIV,
PATBKG,
PATOTH,
PATBKO,
PATFLR,
PATORD,
PATWIR,
PATALO,
PFDCOM,
PFDFE1,
PFDFE2,
PFDFE3,
PFDFE4,
PFDFE5,
PFDFE6,
PFDFE7,
PFDFE8,
PFDFE9,
PFDGIV,
PFDBKG,
PFDOTH,
PFDBKO,
PFDFLR,
PFDORD,
PFDWIR,
PFDALO,
PFUFE1,
PFUFE2,
PFUFE3,
PFUFE4,
PFUFE5,
PFUFE6,
PFUFE7,
PFUFE8,
PFUFE9,
PFUGIV,
PFUBKG,
PFUOTH,
PFUBKO,
PFUFLR,
PFUORD,
PFUWIR,
PFUALO,
POVNQ,
PDAYQ,
PSCRQ,
PSPDQ,
POVNC,
PDAYC,
PSCRC,
PSPDC,
PSORTK,
PLEVEL,
PBATCH,
PRECNO,
PCLRID,
PINPMO,
PINPYR,
PFBACC,
PORIG,
PCABCD,
PSCHOV,
PPGMID,
PSCRID,
PUSER,
PWSID,
PWSTIM,
PDEST,
PDELET,
PXTRCT,
PBQTY,
PSQTY,
PFDAM1,
PAMT1,
PFDAM2,
PAMT2,
PROUT1,
PROUT2,
PROUT3,
PCURAC,
PCURAT,
PCCNTY)
SELECT --TOP 10000
CONVERT(VARCHAR(1),REPLACE(PRECID,'"','')), --PRECID
CONVERT(VARCHAR(1),PFIRM), --PFIRM
CONVERT(VARCHAR(3),POFFIC), --POFFIC
CONVERT(VARCHAR(5),PACCT), --PACCT
CONVERT(VARCHAR(2),PATYPE), --PATYPE
CONVERT(VARCHAR(12),PCUSIP), --PCUSIP
CONVERT(VARCHAR(12),PCUSP2), --PCUSP2
CONVERT(VARCHAR(6),PCTYM), --PCTYM
CONVERT(VARCHAR(2),PSBCUS), --PSBCUS
CONVERT(VARCHAR(1),PSTYPE), --PSTYPE
CONVERT(VARCHAR(1),PSUBTY), --PSUBTY
CONVERT(VARCHAR(1),PSTYP2), --PSTYP2
CONVERT(NUMERIC(15,8),PSTRIK), --PSTRIK
CONVERT(NUMERIC(9,0),PEXPDT), --PEXPDT
CONVERT(VARCHAR(10),PSUBAC), --PSUBAC
CONVERT(VARCHAR(7),PDEAL), --PDEAL
CONVERT(NUMERIC(9,0),PTDATE), --PTDATE
CONVERT(NUMERIC(15,8),PTPRIC), --PTPRIC
CONVERT(VARCHAR(1),PBS), --PBS
CONVERT(VARCHAR(1),PLOC), --PLOC
CONVERT(VARCHAR(2),PBROKR), --PBROKR
CONVERT(VARCHAR(1),PSPRED), --PSPRED
CONVERT(VARCHAR(10),PTRACE), --PTRACE
CONVERT(VARCHAR(3),PICODE), --PICODE
CONVERT(VARCHAR(12),PREFNO), --PREFNO
CONVERT(VARCHAR(12),PSWAC1), --PSWAC1
CONVERT(VARCHAR(1),PSWAP1), --PSWAP1
CONVERT(VARCHAR(1),PSWAS1), --PSWAS1
CONVERT(VARCHAR(12),PSWAC2), --PSWAC2
CONVERT(VARCHAR(1),PSWAP2), --PSWAP2
CONVERT(VARCHAR(1),PSWAS2), --PSWAS2
CONVERT(VARCHAR(1),PZONE), --PZONE
CONVERT(VARCHAR(2),PACNTY), --PACNTY
CONVERT(VARCHAR(1),PCLASS), --PCLASS
CONVERT(VARCHAR(1),PSUBCL), --PSUBCL
CONVERT(VARCHAR(5),PRR), --PRR
CONVERT(VARCHAR(3),PRISKG), --PRISKG
CONVERT(VARCHAR(1),PMEMBR), --PMEMBR
CONVERT(VARCHAR(20),PSNAME), --PSNAME
CONVERT(VARCHAR(10),PSRCAC), --PSRCAC
CONVERT(VARCHAR(3),PREFOF), --PREFOF
CONVERT(VARCHAR(5),PREFRR), --PREFRR
CONVERT(VARCHAR(1),POFFFN), --POFFFN
CONVERT(VARCHAR(3),POFFOF), --POFFOF
CONVERT(VARCHAR(5),POFFAC), --POFFAC
CONVERT(VARCHAR(2),POFFAT), --POFFAT
CONVERT(VARCHAR(2),PMPGMN), --PMPGMN
CONVERT(VARCHAR(1),PSTATA), --PSTATA
CONVERT(VARCHAR(1),PSTATB), --PSTATB
CONVERT(VARCHAR(1),PSTATC), --PSTATC
CONVERT(VARCHAR(1),PSTATD), --PSTATD
CONVERT(VARCHAR(1),PSTATE), --PSTATE
CONVERT(VARCHAR(1),PSTATF), --PSTATF
CONVERT(VARCHAR(1),PSTATG), --PSTATG
CONVERT(VARCHAR(1),PSTATH), --PSTATH
CONVERT(VARCHAR(1),PSTATJ), --PSTATJ
CONVERT(VARCHAR(1),PSTATK), --PSTATK
CONVERT(VARCHAR(1),PSTAT1), --PSTAT1
CONVERT(VARCHAR(1),PSTAT2), --PSTAT2
CONVERT(VARCHAR(1),PSTAT3), --PSTAT3
CONVERT(VARCHAR(1),PSTAT4), --PSTAT4
CONVERT(VARCHAR(1),PSTAT5), --PSTAT5
CONVERT(VARCHAR(1),PSTAT6), --PSTAT6
CONVERT(VARCHAR(1),PSTAT7), --PSTAT7
CONVERT(VARCHAR(1),PSTAT8), --PSTAT8
CONVERT(VARCHAR(1),PSTAT9), --PSTAT9
CONVERT(VARCHAR(1),PQTEDT), --PQTEDT
CONVERT(NUMERIC(15,4),PQTY), --PQTY
CONVERT(VARCHAR(15),PPRTQ), --PPRTQ
CONVERT(NUMERIC(15,4),PBUSTQ), --PBUSTQ
CONVERT(NUMERIC(15,4),PMAKEQ), --PMAKEQ
CONVERT(NUMERIC(15,4),PLEAVQ), --PLEAVQ
CONVERT(NUMERIC(15,4),PSEGQ), --PSEGQ
CONVERT(NUMERIC(15,4),PTFRQ), --PTFRQ
CONVERT(NUMERIC(15,4),PDLVYQ), --PDLVYQ
CONVERT(NUMERIC(15,2),PDLVYA), --PDLVYA
CONVERT(NUMERIC(1,0),PSDSC#), --PSDSC#
CONVERT(VARCHAR(30),PSDSC1), --PSDSC1
CONVERT(VARCHAR(30),PSDSC2), --PSDSC2
CONVERT(VARCHAR(30),PSDSC3), --PSDSC3
CONVERT(NUMERIC(1,0),PTDSC#), --PTDSC#
CONVERT(VARCHAR(30),PTDSC1), --PTDSC1
CONVERT(VARCHAR(30),PTDSC2), --PTDSC2
CONVERT(VARCHAR(30),PTDSC3), --PTDSC3
CONVERT(NUMERIC(15,2),PMKVAL), --PMKVAL
CONVERT(NUMERIC(15,2),PYSTMV), --PYSTMV
CONVERT(NUMERIC(15,7),PMULTF), --PMULTF
CONVERT(NUMERIC(9,0),PSDATE), --PSDATE
CONVERT(NUMERIC(15,8),PEXRAT), --PEXRAT
CONVERT(NUMERIC(9,0),PRXDAT), --PRXDAT
CONVERT(NUMERIC(9,3),PIAD), --PIAD
CONVERT(NUMERIC(9,8),PYIELD), --PYIELD
CONVERT(NUMERIC(15,8),PDCTCO), --PDCTCO
CONVERT(NUMERIC(5,4),PDELTA), --PDELTA
CONVERT(NUMERIC(9,0),PLTDAT), --PLTDAT
CONVERT(VARCHAR(10),PCTLNO), --PCTLNO
CONVERT(VARCHAR(2),PPCNTY), --PPCNTY
CONVERT(VARCHAR(2),PEXCH), --PEXCH
CONVERT(VARCHAR(2),PFC), --PFC
CONVERT(VARCHAR(1),PTYPE), --PTYPE
CONVERT(VARCHAR(6),PSYMBL), --PSYMBL
CONVERT(VARCHAR(1),PPTYPE), --PPTYPE
CONVERT(VARCHAR(1),PSUBEX), --PSUBEX
CONVERT(VARCHAR(2),PTRDEX), --PTRDEX
CONVERT(NUMERIC(9,0),PMATDT), --PMATDT
CONVERT(VARCHAR(11),PPRTPR), --PPRTPR
CONVERT(NUMERIC(9,8),PBASIS), --PBASIS
CONVERT(NUMERIC(15,8),PCLOSE), --PCLOSE
CONVERT(NUMERIC(9,0),PPRCDT), --PPRCDT
CONVERT(VARCHAR(11),PPRTCP), --PPRTCP
CONVERT(NUMERIC(15,8),PUNDCP), --PUNDCP
CONVERT(VARCHAR(11),PPRTUC), --PPRTUC
CONVERT(NUMERIC(15,8),PPRVCP), --PPRVCP
CONVERT(NUMERIC(15,8),PTRPRC), --PTRPRC
CONVERT(VARCHAR(7),PEXPR), --PEXPR
CONVERT(VARCHAR(12),PPRICE), --PPRICE
CONVERT(VARCHAR(1),PSPEDT), --PSPEDT
CONVERT(VARCHAR(1),PTPEDT), --PTPEDT
CONVERT(VARCHAR(3),PCURSY), --PCURSY
CONVERT(VARCHAR(2),PCURCD), --PCURCD
CONVERT(VARCHAR(1),PCALC), --PCALC
CONVERT(VARCHAR(2),PCMNT1), --PCMNT1
CONVERT(VARCHAR(2),PCMNT2), --PCMNT2
CONVERT(VARCHAR(2),PCMNT3), --PCMNT3
CONVERT(VARCHAR(2),PLEGND), --PLEGND
CONVERT(VARCHAR(1),POMNCD), --POMNCD
CONVERT(VARCHAR(1),PRTHT), --PRTHT
CONVERT(VARCHAR(2),PSCHDL), --PSCHDL
CONVERT(VARCHAR(1),POC), --POC
CONVERT(VARCHAR(1),PCOD), --PCOD
CONVERT(VARCHAR(12),PUCUSP), --PUCUSP
CONVERT(NUMERIC(15,8),PCVTBL), --PCVTBL
CONVERT(VARCHAR(5),PEXBKR), --PEXBKR
CONVERT(VARCHAR(5),POPBKR), --POPBKR
CONVERT(VARCHAR(5),POPFRM), --POPFRM
CONVERT(VARCHAR(2),PGIVIO), --PGIVIO
CONVERT(VARCHAR(5),PGIVF#), --PGIVF#
CONVERT(VARCHAR(2),PIEXNG), --PIEXNG
CONVERT(VARCHAR(5),PIEFRM), --PIEFRM
CONVERT(VARCHAR(4),PCARD), --PCARD
CONVERT(VARCHAR(25),PORDER), --PORDER
CONVERT(VARCHAR(15),PCHIT), --PCHIT
CONVERT(VARCHAR(1),PFEECL), --PFEECL
CONVERT(VARCHAR(1),PFEEEX), --PFEEEX
CONVERT(VARCHAR(1),PCTI), --PCTI
CONVERT(VARCHAR(3),PORDTY), --PORDTY
CONVERT(VARCHAR(2),PORDOR), --PORDOR
CONVERT(VARCHAR(6),PTIME), --PTIME
CONVERT(VARCHAR(2),PTBKT), --PTBKT
CONVERT(VARCHAR(1),PSESSN), --PSESSN
CONVERT(VARCHAR(2),PSTINS), --PSTINS
CONVERT(VARCHAR(1),PTTYPE), --PTTYPE
CONVERT(VARCHAR(2),PBARG1), --PBARG1
CONVERT(VARCHAR(2),PBARG2), --PBARG2
CONVERT(VARCHAR(2),PBARG3), --PBARG3
CONVERT(VARCHAR(2),PBARG4), --PBARG4
CONVERT(VARCHAR(2),PBARG5), --PBARG5
CONVERT(VARCHAR(1),PMTABL), --PMTABL
CONVERT(NUMERIC(15,2),PMINIT), --PMINIT
CONVERT(NUMERIC(15,2),PMVARN), --PMVARN
CONVERT(NUMERIC(9,0),PMUNTL), --PMUNTL
CONVERT(NUMERIC(15,2),PMGNCV), --PMGNCV
CONVERT(VARCHAR(1),PREL1F), --PREL1F
CONVERT(VARCHAR(3),PREL1O), --PREL1O
CONVERT(VARCHAR(5),PREL1A), --PREL1A
CONVERT(VARCHAR(1),PREL1T), --PREL1T
CONVERT(VARCHAR(1),PREL2F), --PREL2F
CONVERT(VARCHAR(3),PREL2O), --PREL2O
CONVERT(VARCHAR(5),PREL2A), --PREL2A
CONVERT(VARCHAR(1),PREL2T), --PREL2T
CONVERT(VARCHAR(1),PREL3F), --PREL3F
CONVERT(VARCHAR(3),PREL3O), --PREL3O
CONVERT(VARCHAR(5),PREL3A), --PREL3A
CONVERT(VARCHAR(1),PREL3T), --PREL3T
CONVERT(NUMERIC(15,2),PCOMM), --PCOMM
CONVERT(NUMERIC(15,2),PFEE1), --PFEE1
CONVERT(NUMERIC(15,2),PFEE2), --PFEE2
CONVERT(NUMERIC(15,2),PFEE3), --PFEE3
CONVERT(NUMERIC(15,2),PFEE4), --PFEE4
CONVERT(NUMERIC(15,2),PFEE5), --PFEE5
CONVERT(NUMERIC(15,2),PFEE6), --PFEE6
CONVERT(NUMERIC(15,2),PFEE7), --PFEE7
CONVERT(NUMERIC(15,2),PFEE8), --PFEE8
CONVERT(NUMERIC(15,2),PFEE9), --PFEE9
CONVERT(NUMERIC(15,2),PGICHG), --PGICHG
CONVERT(NUMERIC(15,2),PBKCHG), --PBKCHG
CONVERT(NUMERIC(15,2),POTHER), --POTHER
CONVERT(NUMERIC(15,2),PGROSS), --PGROSS
CONVERT(NUMERIC(15,2),PNET), --PNET
CONVERT(NUMERIC(15,2),PMBKOF), --PMBKOF
CONVERT(NUMERIC(15,2),PMFLOR), --PMFLOR
CONVERT(NUMERIC(15,2),PMORDR), --PMORDR
CONVERT(NUMERIC(15,2),PMWIRE), --PMWIRE
CONVERT(NUMERIC(15,2),PMOTHR), --PMOTHR
CONVERT(VARCHAR(2),PATCOM), --PATCOM
CONVERT(VARCHAR(2),PATFE1), --PATFE1
CONVERT(VARCHAR(2),PATFE2), --PATFE2
CONVERT(VARCHAR(2),PATFE3), --PATFE3
CONVERT(VARCHAR(2),PATFE4), --PATFE4
CONVERT(VARCHAR(2),PATFE5), --PATFE5
CONVERT(VARCHAR(2),PATFE6), --PATFE6
CONVERT(VARCHAR(2),PATFE7), --PATFE7
CONVERT(VARCHAR(2),PATFE8), --PATFE8
CONVERT(VARCHAR(2),PATFE9), --PATFE9
CONVERT(VARCHAR(2),PATGIV), --PATGIV
CONVERT(VARCHAR(2),PATBKG), --PATBKG
CONVERT(VARCHAR(2),PATOTH), --PATOTH
CONVERT(VARCHAR(2),PATBKO), --PATBKO
CONVERT(VARCHAR(2),PATFLR), --PATFLR
CONVERT(VARCHAR(2),PATORD), --PATORD
CONVERT(VARCHAR(2),PATWIR), --PATWIR
CONVERT(VARCHAR(2),PATALO), --PATALO
CONVERT(VARCHAR(1),PFDCOM), --PFDCOM
CONVERT(VARCHAR(1),PFDFE1), --PFDFE1
CONVERT(VARCHAR(1),PFDFE2), --PFDFE2
CONVERT(VARCHAR(1),PFDFE3), --PFDFE3
CONVERT(VARCHAR(1),PFDFE4), --PFDFE4
CONVERT(VARCHAR(1),PFDFE5), --PFDFE5
CONVERT(VARCHAR(1),PFDFE6), --PFDFE6
CONVERT(VARCHAR(1),PFDFE7), --PFDFE7
CONVERT(VARCHAR(1),PFDFE8), --PFDFE8
CONVERT(VARCHAR(1),PFDFE9), --PFDFE9
CONVERT(VARCHAR(1),PFDGIV), --PFDGIV
CONVERT(VARCHAR(1),PFDBKG), --PFDBKG
CONVERT(VARCHAR(1),PFDOTH), --PFDOTH
CONVERT(VARCHAR(1),PFDBKO), --PFDBKO
CONVERT(VARCHAR(1),PFDFLR), --PFDFLR
CONVERT(VARCHAR(1),PFDORD), --PFDORD
CONVERT(VARCHAR(1),PFDWIR), --PFDWIR
CONVERT(VARCHAR(1),PFDALO), --PFDALO
CONVERT(VARCHAR(1),PFUFE1), --PFUFE1
CONVERT(VARCHAR(1),PFUFE2), --PFUFE2
CONVERT(VARCHAR(1),PFUFE3), --PFUFE3
CONVERT(VARCHAR(1),PFUFE4), --PFUFE4
CONVERT(VARCHAR(1),PFUFE5), --PFUFE5
CONVERT(VARCHAR(1),PFUFE6), --PFUFE6
CONVERT(VARCHAR(1),PFUFE7), --PFUFE7
CONVERT(VARCHAR(1),PFUFE8), --PFUFE8
CONVERT(VARCHAR(1),PFUFE9), --PFUFE9
CONVERT(VARCHAR(1),PFUGIV), --PFUGIV
CONVERT(VARCHAR(1),PFUBKG), --PFUBKG
CONVERT(VARCHAR(1),PFUOTH), --PFUOTH
CONVERT(VARCHAR(1),PFUBKO), --PFUBKO
CONVERT(VARCHAR(1),PFUFLR), --PFUFLR
CONVERT(VARCHAR(1),PFUORD), --PFUORD
CONVERT(VARCHAR(1),PFUWIR), --PFUWIR
CONVERT(VARCHAR(1),PFUALO), --PFUALO
CONVERT(NUMERIC(15,4),POVNQ), --POVNQ
CONVERT(NUMERIC(15,4),PDAYQ), --PDAYQ
CONVERT(NUMERIC(15,4),PSCRQ), --PSCRQ
CONVERT(NUMERIC(15,4),PSPDQ), --PSPDQ
CONVERT(NUMERIC(15,2),POVNC), --POVNC
CONVERT(NUMERIC(15,2),PDAYC), --PDAYC
CONVERT(NUMERIC(15,2),PSCRC), --PSCRC
CONVERT(NUMERIC(15,2),PSPDC), --PSPDC
CONVERT(VARCHAR(50),PSORTK), --PSORTK
CONVERT(VARCHAR(3),PLEVEL), --PLEVEL
CONVERT(VARCHAR(3),PBATCH), --PBATCH
CONVERT(NUMERIC(7,0),PRECNO), --PRECNO
CONVERT(VARCHAR(10),PCLRID), --PCLRID
CONVERT(VARCHAR(1),PINPMO), --PINPMO
CONVERT(VARCHAR(2),PINPYR), --PINPYR
CONVERT(VARCHAR(5),PFBACC), --PFBACC
CONVERT(VARCHAR(1),PORIG), --PORIG
CONVERT(VARCHAR(1),PCABCD), --PCABCD
CONVERT(VARCHAR(2),PSCHOV), --PSCHOV
CONVERT(VARCHAR(2),PPGMID), --PPGMID
CONVERT(VARCHAR(2),PSCRID), --PSCRID
CONVERT(VARCHAR(10),PUSER), --PUSER
CONVERT(VARCHAR(10),PWSID), --PWSID
CONVERT(NUMERIC(7,0),PWSTIM), --PWSTIM
CONVERT(VARCHAR(1),PDEST), --PDEST
CONVERT(VARCHAR(1),PDELET), --PDELET
CONVERT(NUMERIC(7,0),PXTRCT), --PXTRCT
CONVERT(NUMERIC(15,4),PBQTY), --PBQTY
CONVERT(NUMERIC(15,4),PSQTY), --PSQTY
CONVERT(VARCHAR(1),PFDAM1), --PFDAM1
CONVERT(NUMERIC(15,2),PAMT1), --PAMT1
CONVERT(VARCHAR(1),PFDAM2), --PFDAM2
CONVERT(NUMERIC(15,2),PAMT2), --PAMT2
CONVERT(VARCHAR(1),PROUT1), --PROUT1
CONVERT(VARCHAR(1),PROUT2), --PROUT2
CONVERT(VARCHAR(1),PROUT3), --PROUT3
CONVERT(VARCHAR(3),PCURAC), --PCURAC
CONVERT(VARCHAR(3),PCURAT), --PCURAT
CONVERT(VARCHAR(2),PCCNTY) --PCCNTY
FROM [dbo].[GMIPOSF1_File_Raw]

SELECT @@ROWCOUNT "Records Loaded"

SELECT GETDATE() "End Time"

PRINT '************************************************************************************************************'
PRINT ' [dbo].[PROC_Load_GMIPOSF1_File_Current] ENDED'
PRINT '************************************************************************************************************'
SELECT GETDATE() "End Time"

SET NOCOUNT OFF

GO