DROP PROCEDURE [dbo].[PROC_Load_GMIMNYF1_File_Current]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[PROC_Load_GMIMNYF1_File_Current]

AS

SET NOCOUNT ON

PRINT '************************************************************************************************************'
PRINT ' [dbo].[PROC_Load_GMIMNYF1_File_Current] STARTED'
PRINT '************************************************************************************************************'
SELECT GETDATE() "Start Time"

PRINT '**************************************************************************'
PRINT ' TRUNCATE TABLE [dbo].[GMIMNYF1_File_Current]'
PRINT '**************************************************************************'
TRUNCATE TABLE [dbo].[GMIMNYF1_File_Current]

PRINT '**************************************************************************'
PRINT ' Load [dbo].[GMIMNYF1_File_Current]'
PRINT ' with [dbo].[GMIMNYF1_File_Raw]'
PRINT '**************************************************************************'

SELECT GETDATE() "Start Time"

INSERT INTO [dbo].[GMIMNYF1_File_Current]
(MRECID,
MFIRM,
MOFFIC,
MACCT,
MATYPE,
MRR,
MCLASS,
MSUBCL,
MCURAT,
MCURCD,
MCURAC,
MCURFM,
MCPCOD,
MNCALL,
MCAGE,
MFILL1,
MAVDYS,
MDSCCD,
MOMNCD,
MACNTY,
MMPGMN,
MSNAME,
MNA1,
MDLACT,
MDLACW,
MREL1F,
MREL1O,
MREL1A,
MREL1T,
MREL2F,
MREL2O,
MREL2A,
MREL2T,
MREL3F,
MREL3O,
MREL3A,
MREL3T,
MGRPFM,
MGRPOF,
MGRPRR,
MGRPAC,
MBAL,
MLMV,
MSMV,
MLOV,
MSOV,
MTC,
MWF,
MFIR,
MFMR,
MFEXIR,
MME,
MOTE,
MSMA,
MLOOTE,
MSOOTE,
MAVGEQ,
MMTDCM,
MUNLMV,
MTDBAL,
MUNSMV,
MMMHC,
MUNDPC,
MMTDPL,
MSEGLV,
MSEGSV,
MEIR,
MEMR,
MCVTFB,
MDVBAL,
MJPUPL,
MFOOTE,
MLOANV,
MBYPWR,
MPNDIV,
MPNINT,
MLQVAL,
MMRGVL,
MOTECR,
MOTEDR,
MPREM,
MOOTEC,
MAVSOD,
MLOPRM,
MUNUPL,
MAVGME,
MJPIR,
MJPIRC,
MJPMR,
MJPRT2,
MTAR,
MEPOTE,
MLVUST,
MTE,
MAVGBL,
MAVGOV,
MCVTAB,
MCMACR,
MCMACU,
MSPNOV,
MEEXM,
MEIRT,
MEOIR,
MEOMR,
MFEXMR,
MGEUDC,
MNCOTE,
MCCDNT,
MEQPCT,
MREGCV,
MCVTAF,
MTDVAL,
MTCC,
MMRGLM,
MPNOTH,
MIRCIC,
MIRCEC,
MDEFOT,
MSECAM,
MCLMGN,
MCLOTE,
MSPNAE,
MMVUCI,
MACRET,
MPOOTE,
MUNDEP,
MPRTC,
MPRSMA,
MLVTM4,
MLVTM3,
MLVTM2,
MPREOI,
MPREIR,
MPRFXM,
MPRFXI,
MPRFIR,
MPROTE,
MPRTE,
MPRLQV,
MPRRCV,
MPRBAL,
MBNRY1,
MBNRY2,
MBNRY3,
MBNRY4,
MBNRY5,
MMISC1,
MMISC2,
MMISC3,
MMISC4,
MMISC5,
MMISC6,
MMISC7,
MMISC8,
MMISC9,
MMISC0,
MCND01,
MCND02,
MCND03,
MCND04,
MCND05,
MCND06,
MCND07,
MCND08,
MCND09,
MCND10,
MUSFL1,
MUSFL2,
MUSFL3,
MUSFL4,
MUSFL5,
MUSFL6,
MUSFL7,
MUSFL8,
MUSFL9,
MUSFLA,
MUKFL1,
MUKFL2,
MUKFL3,
MUKFL4,
MFRFL1,
MFRFL2,
MFRFL3,
MJPFL1,
MJPFL2,
MJPFL3,
MHKFL1,
MGEFL1,
MITFL1)
SELECT
CONVERT(VARCHAR(1),REPLACE(MRECID,'"','')), --MRECID
CONVERT(VARCHAR(1),MFIRM), --MFIRM
CONVERT(VARCHAR(3),MOFFIC), --MOFFIC
CONVERT(VARCHAR(5),MACCT), --MACCT
CONVERT(VARCHAR(2),MATYPE), --MATYPE
CONVERT(VARCHAR(5),MRR), --MRR
CONVERT(VARCHAR(1),MCLASS), --MCLASS
CONVERT(VARCHAR(1),MSUBCL), --MSUBCL
CONVERT(VARCHAR(3),MCURAT), --MCURAT
CONVERT(VARCHAR(2),MCURCD), --MCURCD
CONVERT(VARCHAR(3),MCURAC), --MCURAC
CONVERT(VARCHAR(3),MCURFM), --MCURFM
CONVERT(VARCHAR(1),MCPCOD), --MCPCOD
CONVERT(NUMERIC(2,0),MNCALL), --MNCALL
CONVERT(NUMERIC(2,0),MCAGE), --MCAGE
CONVERT(VARCHAR(1),MFILL1), --MFILL1
CONVERT(NUMERIC(2,0),MAVDYS), --MAVDYS
CONVERT(VARCHAR(1),MDSCCD), --MDSCCD
CONVERT(VARCHAR(1),MOMNCD), --MOMNCD
CONVERT(VARCHAR(2),MACNTY), --MACNTY
CONVERT(VARCHAR(2),MMPGMN), --MMPGMN
CONVERT(VARCHAR(20),MSNAME), --MSNAME
CONVERT(VARCHAR(32),MNA1), --MNA1
CONVERT(NUMERIC(9,0),MDLACT), --MDLACT
CONVERT(VARCHAR(9),MDLACW), --MDLACW
CONVERT(VARCHAR(1),MREL1F), --MREL1F
CONVERT(VARCHAR(3),MREL1O), --MREL1O
CONVERT(VARCHAR(5),MREL1A), --MREL1A
CONVERT(VARCHAR(1),MREL1T), --MREL1T
CONVERT(VARCHAR(1),MREL2F), --MREL2F
CONVERT(VARCHAR(3),MREL2O), --MREL2O
CONVERT(VARCHAR(5),MREL2A), --MREL2A
CONVERT(VARCHAR(1),MREL2T), --MREL2T
CONVERT(VARCHAR(1),MREL3F), --MREL3F
CONVERT(VARCHAR(3),MREL3O), --MREL3O
CONVERT(VARCHAR(5),MREL3A), --MREL3A
CONVERT(VARCHAR(1),MREL3T), --MREL3T
CONVERT(VARCHAR(1),MGRPFM), --MGRPFM
CONVERT(VARCHAR(3),MGRPOF), --MGRPOF
CONVERT(VARCHAR(5),MGRPRR), --MGRPRR
CONVERT(VARCHAR(5),MGRPAC), --MGRPAC
CONVERT(NUMERIC(15,2),MBAL), --MBAL
CONVERT(NUMERIC(15,2),MLMV), --MLMV
CONVERT(NUMERIC(15,2),MSMV), --MSMV
CONVERT(NUMERIC(15,2),MLOV), --MLOV
CONVERT(NUMERIC(15,2),MSOV), --MSOV
CONVERT(NUMERIC(15,2),MTC), --MTC
CONVERT(NUMERIC(15,2),MWF), --MWF
CONVERT(NUMERIC(15,2),MFIR), --MFIR
CONVERT(NUMERIC(15,2),MFMR), --MFMR
CONVERT(NUMERIC(15,2),MFEXIR), --MFEXIR
CONVERT(NUMERIC(15,2),MME), --MME
CONVERT(NUMERIC(15,2),MOTE), --MOTE
CONVERT(NUMERIC(15,2),MSMA), --MSMA
CONVERT(NUMERIC(15,2),MLOOTE), --MLOOTE
CONVERT(NUMERIC(15,2),MSOOTE), --MSOOTE
CONVERT(NUMERIC(15,2),MAVGEQ), --MAVGEQ
CONVERT(NUMERIC(15,2),MMTDCM), --MMTDCM
CONVERT(NUMERIC(15,2),MUNLMV), --MUNLMV
CONVERT(NUMERIC(15,2),MTDBAL), --MTDBAL
CONVERT(NUMERIC(15,2),MUNSMV), --MUNSMV
CONVERT(NUMERIC(15,2),MMMHC), --MMMHC
CONVERT(NUMERIC(15,2),MUNDPC), --MUNDPC
CONVERT(NUMERIC(15,2),MMTDPL), --MMTDPL
CONVERT(NUMERIC(15,2),MSEGLV), --MSEGLV
CONVERT(NUMERIC(15,2),MSEGSV), --MSEGSV
CONVERT(NUMERIC(15,2),MEIR), --MEIR
CONVERT(NUMERIC(15,2),MEMR), --MEMR
CONVERT(NUMERIC(15,8),MCVTFB), --MCVTFB
CONVERT(NUMERIC(15,2),MDVBAL), --MDVBAL
CONVERT(NUMERIC(15,2),MJPUPL), --MJPUPL
CONVERT(NUMERIC(15,2),MFOOTE), --MFOOTE
CONVERT(NUMERIC(15,2),MLOANV), --MLOANV
CONVERT(NUMERIC(15,2),MBYPWR), --MBYPWR
CONVERT(NUMERIC(15,2),MPNDIV), --MPNDIV
CONVERT(NUMERIC(15,2),MPNINT), --MPNINT
CONVERT(NUMERIC(15,2),MLQVAL), --MLQVAL
CONVERT(NUMERIC(15,2),MMRGVL), --MMRGVL
CONVERT(NUMERIC(15,2),MOTECR), --MOTECR
CONVERT(NUMERIC(15,2),MOTEDR), --MOTEDR
CONVERT(NUMERIC(15,2),MPREM), --MPREM
CONVERT(NUMERIC(15,2),MOOTEC), --MOOTEC
CONVERT(NUMERIC(15,2),MAVSOD), --MAVSOD
CONVERT(NUMERIC(15,2),MLOPRM), --MLOPRM
CONVERT(NUMERIC(15,2),MUNUPL), --MUNUPL
CONVERT(NUMERIC(15,2),MAVGME), --MAVGME
CONVERT(NUMERIC(15,2),MJPIR), --MJPIR
CONVERT(NUMERIC(15,2),MJPIRC), --MJPIRC
CONVERT(NUMERIC(15,2),MJPMR), --MJPMR
CONVERT(NUMERIC(15,2),MJPRT2), --MJPRT2
CONVERT(NUMERIC(15,2),MTAR), --MTAR
CONVERT(NUMERIC(15,2),MEPOTE), --MEPOTE
CONVERT(NUMERIC(15,2),MLVUST), --MLVUST
CONVERT(NUMERIC(15,2),MTE), --MTE
CONVERT(NUMERIC(15,2),MAVGBL), --MAVGBL
CONVERT(NUMERIC(15,2),MAVGOV), --MAVGOV
CONVERT(NUMERIC(15,8),MCVTAB), --MCVTAB
CONVERT(NUMERIC(15,2),MCMACR), --MCMACR
CONVERT(NUMERIC(15,2),MCMACU), --MCMACU
CONVERT(NUMERIC(15,2),MSPNOV), --MSPNOV
CONVERT(NUMERIC(15,2),MEEXM), --MEEXM
CONVERT(NUMERIC(15,2),MEIRT), --MEIRT
CONVERT(NUMERIC(15,2),MEOIR), --MEOIR
CONVERT(NUMERIC(15,2),MEOMR), --MEOMR
CONVERT(NUMERIC(15,2),MFEXMR), --MFEXMR
CONVERT(NUMERIC(15,2),MGEUDC), --MGEUDC
CONVERT(NUMERIC(15,2),MNCOTE), --MNCOTE
CONVERT(NUMERIC(15,2),MCCDNT), --MCCDNT
CONVERT(NUMERIC(15,2),MEQPCT), --MEQPCT
CONVERT(NUMERIC(15,2),MREGCV), --MREGCV
CONVERT(NUMERIC(15,8),MCVTAF), --MCVTAF
CONVERT(NUMERIC(15,2),MTDVAL), --MTDVAL
CONVERT(NUMERIC(15,2),MTCC), --MTCC
CONVERT(NUMERIC(15,2),MMRGLM), --MMRGLM
CONVERT(NUMERIC(15,2),MPNOTH), --MPNOTH
CONVERT(NUMERIC(15,2),MIRCIC), --MIRCIC
CONVERT(NUMERIC(15,2),MIRCEC), --MIRCEC
CONVERT(NUMERIC(15,2),MDEFOT), --MDEFOT
CONVERT(NUMERIC(15,2),MSECAM), --MSECAM
CONVERT(NUMERIC(15,2),MCLMGN), --MCLMGN
CONVERT(NUMERIC(15,2),MCLOTE), --MCLOTE
CONVERT(NUMERIC(15,2),MSPNAE), --MSPNAE
CONVERT(NUMERIC(15,2),MMVUCI), --MMVUCI
CONVERT(NUMERIC(15,2),MACRET), --MACRET
CONVERT(NUMERIC(15,2),MPOOTE), --MPOOTE
CONVERT(NUMERIC(15,2),MUNDEP), --MUNDEP
CONVERT(NUMERIC(15,2),MPRTC), --MPRTC
CONVERT(NUMERIC(5,2),MPRSMA), --MPRSMA
CONVERT(NUMERIC(15,2),MLVTM4), --MLVTM4
CONVERT(NUMERIC(15,2),MLVTM3), --MLVTM3
CONVERT(NUMERIC(15,2),MLVTM2), --MLVTM2
CONVERT(NUMERIC(15,2),MPREOI), --MPREOI
CONVERT(NUMERIC(15,2),MPREIR), --MPREIR
CONVERT(NUMERIC(15,2),MPRFXM), --MPRFXM
CONVERT(NUMERIC(15,2),MPRFXI), --MPRFXI
CONVERT(NUMERIC(15,2),MPRFIR), --MPRFIR
CONVERT(NUMERIC(15,2),MPROTE), --MPROTE
CONVERT(NUMERIC(15,2),MPRTE), --MPRTE
CONVERT(NUMERIC(15,2),MPRLQV), --MPRLQV
CONVERT(NUMERIC(15,2),MPRRCV), --MPRRCV
CONVERT(NUMERIC(15,2),MPRBAL), --MPRBAL
CONVERT(VARCHAR(1),MBNRY1), --MBNRY1
CONVERT(VARCHAR(1),MBNRY2), --MBNRY2
CONVERT(VARCHAR(1),MBNRY3), --MBNRY3
CONVERT(VARCHAR(1),MBNRY4), --MBNRY4
CONVERT(VARCHAR(1),MBNRY5), --MBNRY5
CONVERT(VARCHAR(1),MMISC1), --MMISC1
CONVERT(VARCHAR(1),MMISC2), --MMISC2
CONVERT(VARCHAR(1),MMISC3), --MMISC3
CONVERT(VARCHAR(1),MMISC4), --MMISC4
CONVERT(VARCHAR(1),MMISC5), --MMISC5
CONVERT(VARCHAR(1),MMISC6), --MMISC6
CONVERT(VARCHAR(1),MMISC7), --MMISC7
CONVERT(VARCHAR(1),MMISC8), --MMISC8
CONVERT(VARCHAR(1),MMISC9), --MMISC9
CONVERT(VARCHAR(1),MMISC0), --MMISC0
CONVERT(VARCHAR(1),MCND01), --MCND01
CONVERT(VARCHAR(1),MCND02), --MCND02
CONVERT(VARCHAR(1),MCND03), --MCND03
CONVERT(VARCHAR(1),MCND04), --MCND04
CONVERT(VARCHAR(1),MCND05), --MCND05
CONVERT(VARCHAR(1),MCND06), --MCND06
CONVERT(VARCHAR(1),MCND07), --MCND07
CONVERT(VARCHAR(1),MCND08), --MCND08
CONVERT(VARCHAR(1),MCND09), --MCND09
CONVERT(VARCHAR(1),MCND10), --MCND10
CONVERT(VARCHAR(1),MUSFL1), --MUSFL1
CONVERT(VARCHAR(1),MUSFL2), --MUSFL2
CONVERT(VARCHAR(1),MUSFL3), --MUSFL3
CONVERT(VARCHAR(1),MUSFL4), --MUSFL4
CONVERT(VARCHAR(1),MUSFL5), --MUSFL5
CONVERT(VARCHAR(1),MUSFL6), --MUSFL6
CONVERT(VARCHAR(1),MUSFL7), --MUSFL7
CONVERT(VARCHAR(1),MUSFL8), --MUSFL8
CONVERT(VARCHAR(1),MUSFL9), --MUSFL9
CONVERT(VARCHAR(1),MUSFLA), --MUSFLA
CONVERT(VARCHAR(1),MUKFL1), --MUKFL1
CONVERT(VARCHAR(1),MUKFL2), --MUKFL2
CONVERT(VARCHAR(2),MUKFL3), --MUKFL3
CONVERT(VARCHAR(1),MUKFL4), --MUKFL4
CONVERT(VARCHAR(1),MFRFL1), --MFRFL1
CONVERT(VARCHAR(1),MFRFL2), --MFRFL2
CONVERT(VARCHAR(1),MFRFL3), --MFRFL3
CONVERT(VARCHAR(1),MJPFL1), --MJPFL1
CONVERT(VARCHAR(1),MJPFL2), --MJPFL2
CONVERT(VARCHAR(1),MJPFL3), --MJPFL3
CONVERT(VARCHAR(1),MHKFL1), --MHKFL1
CONVERT(VARCHAR(1),MGEFL1), --MGEFL1
CONVERT(VARCHAR(1),MITFL1) --MITFL1
FROM [dbo].[GMIMNYF1_File_Raw]

SELECT @@ROWCOUNT "Records Loaded"

SELECT GETDATE() "End Time"

PRINT '************************************************************************************************************'
PRINT ' [dbo].[PROC_Load_GMIMNYF1_File_Current] ENDED'
PRINT '************************************************************************************************************'
SELECT GETDATE() "End Time"


SET NOCOUNT OFF

GO