USE master
GO

SET NOCOUNT ON

ALTER DATABASE GMIDATA
    MODIFY FILE (NAME = 'GMIDATA', FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\GMIDATA.mdf');

SET NOCOUNT OFF