DROP TABLE [dbo].[DOREMAILA3_File_Raw]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[DOREMAILA3_File_Raw](
	[MFUNC] [varchar](255) NOT NULL DEFAULT '',
	[MSEQ] [varchar](255) NOT NULL DEFAULT '',
	[MFIRM] [varchar](255) NOT NULL DEFAULT '',
	[MOFFIC] [varchar](255) NOT NULL DEFAULT '',
	[MACCT] [varchar](255) NOT NULL DEFAULT '',
	[YRR] [varchar](255) NOT NULL DEFAULT '',
	[MTRMID] [varchar](255) NOT NULL DEFAULT '',
	[MADRS1] [varchar](255) NOT NULL DEFAULT '',
	[MADRS2] [varchar](255) NOT NULL DEFAULT '',
	[MADRS3] [varchar](255) NOT NULL DEFAULT '',
	[MADRS4] [varchar](255) NOT NULL DEFAULT ''

) ON [PRIMARY]
GO

SET ANSI_PADDING OFF
GO