USE [GMIDATA]
GO

DROP TABLE [dbo].[GMIMNYF1_File_History]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[GMIMNYF1_File_History](
	[Processing_Date] [date],
	[MRECID] [varchar](255) NOT NULL,
	[MFIRM] [varchar](255) NOT NULL,
	[MOFFIC] [varchar](255) NOT NULL,
	[MACCT] [varchar](255) NOT NULL,
	[MATYPE] [varchar](255) NOT NULL,
	[MRR] [varchar](255) NOT NULL,
	[MCLASS] [varchar](255) NOT NULL,
	[MSUBCL] [varchar](255) NOT NULL,
	[MCURAT] [varchar](255) NOT NULL,
	[MCURCD] [varchar](255) NOT NULL,
	[MCURAC] [varchar](255) NOT NULL,
	[MCURFM] [varchar](255) NOT NULL,
	[MCPCOD] [varchar](255) NOT NULL,
	[MNCALL] [varchar](255) NOT NULL,
	[MCAGE] [varchar](255) NOT NULL,
	[MFILL1] [varchar](255) NOT NULL,
	[MAVDYS] [varchar](255) NOT NULL,
	[MDSCCD] [varchar](255) NOT NULL,
	[MOMNCD] [varchar](255) NOT NULL,
	[MACNTY] [varchar](255) NOT NULL,
	[MMPGMN] [varchar](255) NOT NULL,
	[MSNAME] [varchar](255) NOT NULL,
	[MNA1] [varchar](255) NOT NULL,
	[MDLACT] [varchar](255) NOT NULL,
	[MDLACW] [varchar](255) NOT NULL,
	[MREL1F] [varchar](255) NOT NULL,
	[MREL1O] [varchar](255) NOT NULL,
	[MREL1A] [varchar](255) NOT NULL,
	[MREL1T] [varchar](255) NOT NULL,
	[MREL2F] [varchar](255) NOT NULL,
	[MREL2O] [varchar](255) NOT NULL,
	[MREL2A] [varchar](255) NOT NULL,
	[MREL2T] [varchar](255) NOT NULL,
	[MREL3F] [varchar](255) NOT NULL,
	[MREL3O] [varchar](255) NOT NULL,
	[MREL3A] [varchar](255) NOT NULL,
	[MREL3T] [varchar](255) NOT NULL,
	[MGRPFM] [varchar](255) NOT NULL,
	[MGRPOF] [varchar](255) NOT NULL,
	[MGRPRR] [varchar](255) NOT NULL,
	[MGRPAC] [varchar](255) NOT NULL,
	[MBAL] [varchar](255) NOT NULL,
	[MLMV] [varchar](255) NOT NULL,
	[MSMV] [varchar](255) NOT NULL,
	[MLOV] [varchar](255) NOT NULL,
	[MSOV] [varchar](255) NOT NULL,
	[MTC] [varchar](255) NOT NULL,
	[MWF] [varchar](255) NOT NULL,
	[MFIR] [varchar](255) NOT NULL,
	[MFMR] [varchar](255) NOT NULL,
	[MFEXIR] [varchar](255) NOT NULL,
	[MME] [varchar](255) NOT NULL,
	[MOTE] [varchar](255) NOT NULL,
	[MSMA] [varchar](255) NOT NULL,
	[MLOOTE] [varchar](255) NOT NULL,
	[MSOOTE] [varchar](255) NOT NULL,
	[MAVGEQ] [varchar](255) NOT NULL,
	[MMTDCM] [varchar](255) NOT NULL,
	[MUNLMV] [varchar](255) NOT NULL,
	[MTDBAL] [varchar](255) NOT NULL,
	[MUNSMV] [varchar](255) NOT NULL,
	[MMMHC] [varchar](255) NOT NULL,
	[MUNDPC] [varchar](255) NOT NULL,
	[MMTDPL] [varchar](255) NOT NULL,
	[MSEGLV] [varchar](255) NOT NULL,
	[MSEGSV] [varchar](255) NOT NULL,
	[MEIR] [varchar](255) NOT NULL,
	[MEMR] [varchar](255) NOT NULL,
	[MCVTFB] [varchar](255) NOT NULL,
	[MDVBAL] [varchar](255) NOT NULL,
	[MJPUPL] [varchar](255) NOT NULL,
	[MFOOTE] [varchar](255) NOT NULL,
	[MLOANV] [varchar](255) NOT NULL,
	[MBYPWR] [varchar](255) NOT NULL,
	[MPNDIV] [varchar](255) NOT NULL,
	[MPNINT] [varchar](255) NOT NULL,
	[MLQVAL] [varchar](255) NOT NULL,
	[MMRGVL] [varchar](255) NOT NULL,
	[MOTECR] [varchar](255) NOT NULL,
	[MOTEDR] [varchar](255) NOT NULL,
	[MPREM] [varchar](255) NOT NULL,
	[MOOTEC] [varchar](255) NOT NULL,
	[MAVSOD] [varchar](255) NOT NULL,
	[MLOPRM] [varchar](255) NOT NULL,
	[MUNUPL] [varchar](255) NOT NULL,
	[MAVGME] [varchar](255) NOT NULL,
	[MJPIR] [varchar](255) NOT NULL,
	[MJPIRC] [varchar](255) NOT NULL,
	[MJPMR] [varchar](255) NOT NULL,
	[MJPRT2] [varchar](255) NOT NULL,
	[MTAR] [varchar](255) NOT NULL,
	[MEPOTE] [varchar](255) NOT NULL,
	[MLVUST] [varchar](255) NOT NULL,
	[MTE] [varchar](255) NOT NULL,
	[MAVGBL] [varchar](255) NOT NULL,
	[MAVGOV] [varchar](255) NOT NULL,
	[MCVTAB] [varchar](255) NOT NULL,
	[MCMACR] [varchar](255) NOT NULL,
	[MCMACU] [varchar](255) NOT NULL,
	[MSPNOV] [varchar](255) NOT NULL,
	[MEEXM] [varchar](255) NOT NULL,
	[MEIRT] [varchar](255) NOT NULL,
	[MEOIR] [varchar](255) NOT NULL,
	[MEOMR] [varchar](255) NOT NULL,
	[MFEXMR] [varchar](255) NOT NULL,
	[MGEUDC] [varchar](255) NOT NULL,
	[MNCOTE] [varchar](255) NOT NULL,
	[MCCDNT] [varchar](255) NOT NULL,
	[MEQPCT] [varchar](255) NOT NULL,
	[MREGCV] [varchar](255) NOT NULL,
	[MCVTAF] [varchar](255) NOT NULL,
	[MTDVAL] [varchar](255) NOT NULL,
	[MTCC] [varchar](255) NOT NULL,
	[MMRGLM] [varchar](255) NOT NULL,
	[MPNOTH] [varchar](255) NOT NULL,
	[MIRCIC] [varchar](255) NOT NULL,
	[MIRCEC] [varchar](255) NOT NULL,
	[MDEFOT] [varchar](255) NOT NULL,
	[MSECAM] [varchar](255) NOT NULL,
	[MCLMGN] [varchar](255) NOT NULL,
	[MCLOTE] [varchar](255) NOT NULL,
	[MSPNAE] [varchar](255) NOT NULL,
	[MMVUCI] [varchar](255) NOT NULL,
	[MACRET] [varchar](255) NOT NULL,
	[MPOOTE] [varchar](255) NOT NULL,
	[MUNDEP] [varchar](255) NOT NULL,
	[MPRTC] [varchar](255) NOT NULL,
	[MPRSMA] [varchar](255) NOT NULL,
	[MLVTM4] [varchar](255) NOT NULL,
	[MLVTM3] [varchar](255) NOT NULL,
	[MLVTM2] [varchar](255) NOT NULL,
	[MPREOI] [varchar](255) NOT NULL,
	[MPREIR] [varchar](255) NOT NULL,
	[MPRFXM] [varchar](255) NOT NULL,
	[MPRFXI] [varchar](255) NOT NULL,
	[MPRFIR] [varchar](255) NOT NULL,
	[MPROTE] [varchar](255) NOT NULL,
	[MPRTE] [varchar](255) NOT NULL,
	[MPRLQV] [varchar](255) NOT NULL,
	[MPRRCV] [varchar](255) NOT NULL,
	[MPRBAL] [varchar](255) NOT NULL,
	[MBNRY1] [varchar](255) NOT NULL,
	[MBNRY2] [varchar](255) NOT NULL,
	[MBNRY3] [varchar](255) NOT NULL,
	[MBNRY4] [varchar](255) NOT NULL,
	[MBNRY5] [varchar](255) NOT NULL,
	[MMISC1] [varchar](255) NOT NULL,
	[MMISC2] [varchar](255) NOT NULL,
	[MMISC3] [varchar](255) NOT NULL,
	[MMISC4] [varchar](255) NOT NULL,
	[MMISC5] [varchar](255) NOT NULL,
	[MMISC6] [varchar](255) NOT NULL,
	[MMISC7] [varchar](255) NOT NULL,
	[MMISC8] [varchar](255) NOT NULL,
	[MMISC9] [varchar](255) NOT NULL,
	[MMISC0] [varchar](255) NOT NULL,
	[MCND01] [varchar](255) NOT NULL,
	[MCND02] [varchar](255) NOT NULL,
	[MCND03] [varchar](255) NOT NULL,
	[MCND04] [varchar](255) NOT NULL,
	[MCND05] [varchar](255) NOT NULL,
	[MCND06] [varchar](255) NOT NULL,
	[MCND07] [varchar](255) NOT NULL,
	[MCND08] [varchar](255) NOT NULL,
	[MCND09] [varchar](255) NOT NULL,
	[MCND10] [varchar](255) NOT NULL,
	[MUSFL1] [varchar](255) NOT NULL,
	[MUSFL2] [varchar](255) NOT NULL,
	[MUSFL3] [varchar](255) NOT NULL,
	[MUSFL4] [varchar](255) NOT NULL,
	[MUSFL5] [varchar](255) NOT NULL,
	[MUSFL6] [varchar](255) NOT NULL,
	[MUSFL7] [varchar](255) NOT NULL,
	[MUSFL8] [varchar](255) NOT NULL,
	[MUSFL9] [varchar](255) NOT NULL,
	[MUSFLA] [varchar](255) NOT NULL,
	[MUKFL1] [varchar](255) NOT NULL,
	[MUKFL2] [varchar](255) NOT NULL,
	[MUKFL3] [varchar](255) NOT NULL,
	[MUKFL4] [varchar](255) NOT NULL,
	[MFRFL1] [varchar](255) NOT NULL,
	[MFRFL2] [varchar](255) NOT NULL,
	[MFRFL3] [varchar](255) NOT NULL,
	[MJPFL1] [varchar](255) NOT NULL,
	[MJPFL2] [varchar](255) NOT NULL,
	[MJPFL3] [varchar](255) NOT NULL,
	[MHKFL1] [varchar](255) NOT NULL,
	[MGEFL1] [varchar](255) NOT NULL,
	[MITFL1] [varchar](255) NOT NULL,
	[DateLoaded] [datetime] NOT NULL,
	[DateLoaded_Local] [datetime] NOT NULL DEFAULT GETDATE()

) ON [PRIMARY]
GO

SET ANSI_PADDING OFF
GO