DROP TABLE [dbo].[GNACMFF4_File_Raw]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[GNACMFF4_File_Raw](
	[YRECID] [varchar](255) NOT NULL DEFAULT '',
	[YFIRM] [varchar](255) NOT NULL DEFAULT '',
	[YOFFIC] [varchar](255) NOT NULL DEFAULT '',
	[YACCT] [varchar](255) NOT NULL DEFAULT '',
	[YFLDID] [varchar](255) NOT NULL DEFAULT '',
	[YDAT50] [varchar](255) NOT NULL DEFAULT '',
	[YDSTFL] [varchar](255) NOT NULL DEFAULT '',
	[YMSTFL] [varchar](255) NOT NULL DEFAULT '',
	[YOPTFL] [varchar](255) NOT NULL DEFAULT '',
	[YTRDFL] [varchar](255) NOT NULL DEFAULT '',
	[YDUMF1] [varchar](255) NOT NULL DEFAULT '',
	[YDUMF2] [varchar](255) NOT NULL DEFAULT '',
	[YUSER] [varchar](255) NOT NULL DEFAULT '',
	[YCHGDT] [varchar](255) NOT NULL DEFAULT ''

) ON [PRIMARY]
GO

SET ANSI_PADDING OFF
GO