USE [GMIDATA]
GO

--------------DROP TABLE [dbo].[MNYF1_File_History]
--------------GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[MNYF1_File_History](
	[Processing_Date] [date],
	[MRECID] [varchar](1) NOT NULL,
	[MFIRM] [varchar](1) NOT NULL,
	[MOFFIC] [varchar](3) NOT NULL,
	[MACCT] [varchar](5) NOT NULL,
	[MATYPE] [varchar](2) NOT NULL,
	[MRR] [varchar](5) NOT NULL,
	[MCLASS] [varchar](1) NOT NULL,
	[MSUBCL] [varchar](1) NOT NULL,
	[MCURAT] [varchar](3) NOT NULL,
	[MCURCD] [varchar](2) NOT NULL,
	[MCURAC] [varchar](3) NOT NULL,
	[MCURFM] [varchar](3) NOT NULL,
	[MCPCOD] [varchar](1) NOT NULL,
	[MNCALL] [numeric](2) NOT NULL,
	[MCAGE] [numeric](2) NOT NULL,
	[MFILL1] [varchar](1) NOT NULL,
	[MAVDYS] [numeric](2) NOT NULL,
	[MDSCCD] [varchar](1) NOT NULL,
	[MOMNCD] [varchar](1) NOT NULL,
	[MACNTY] [varchar](2) NOT NULL,
	[MMPGMN] [varchar](2) NOT NULL,
	[MSNAME] [varchar](20) NOT NULL,
	[MNA1] [varchar](32) NOT NULL,
	[MDLACT] [numeric](9) NOT NULL,
	[MDLACW] [varchar](9) NOT NULL,
	[MREL1F] [varchar](1) NOT NULL,
	[MREL1O] [varchar](3) NOT NULL,
	[MREL1A] [varchar](5) NOT NULL,
	[MREL1T] [varchar](1) NOT NULL,
	[MREL2F] [varchar](1) NOT NULL,
	[MREL2O] [varchar](3) NOT NULL,
	[MREL2A] [varchar](5) NOT NULL,
	[MREL2T] [varchar](1) NOT NULL,
	[MREL3F] [varchar](1) NOT NULL,
	[MREL3O] [varchar](3) NOT NULL,
	[MREL3A] [varchar](5) NOT NULL,
	[MREL3T] [varchar](1) NOT NULL,
	[MGRPFM] [varchar](1) NOT NULL,
	[MGRPOF] [varchar](3) NOT NULL,
	[MGRPRR] [varchar](5) NOT NULL,
	[MGRPAC] [varchar](5) NOT NULL,
	[MBAL] [numeric](15,2) NOT NULL,
	[MLMV] [numeric](15,2) NOT NULL,
	[MSMV] [numeric](15,2) NOT NULL,
	[MLOV] [numeric](15,2) NOT NULL,
	[MSOV] [numeric](15,2) NOT NULL,
	[MTC] [numeric](15,2) NOT NULL,
	[MWF] [numeric](15,2) NOT NULL,
	[MFIR] [numeric](15,2) NOT NULL,
	[MFMR] [numeric](15,2) NOT NULL,
	[MFEXIR] [numeric](15,2) NOT NULL,
	[MME] [numeric](15,2) NOT NULL,
	[MOTE] [numeric](15,2) NOT NULL,
	[MSMA] [numeric](15,2) NOT NULL,
	[MLOOTE] [numeric](15,2) NOT NULL,
	[MSOOTE] [numeric](15,2) NOT NULL,
	[MAVGEQ] [numeric](15,2) NOT NULL,
	[MMTDCM] [numeric](15,2) NOT NULL,
	[MUNLMV] [numeric](15,2) NOT NULL,
	[MTDBAL] [numeric](15,2) NOT NULL,
	[MUNSMV] [numeric](15,2) NOT NULL,
	[MMMHC] [numeric](15,2) NOT NULL,
	[MUNDPC] [numeric](15,2) NOT NULL,
	[MMTDPL] [numeric](15,2) NOT NULL,
	[MSEGLV] [numeric](15,2) NOT NULL,
	[MSEGSV] [numeric](15,2) NOT NULL,
	[MEIR] [numeric](15,2) NOT NULL,
	[MEMR] [numeric](15,2) NOT NULL,
	[MCVTFB] [numeric](15,8) NOT NULL,
	[MDVBAL] [numeric](15,2) NOT NULL,
	[MJPUPL] [numeric](15,2) NOT NULL,
	[MFOOTE] [numeric](15,2) NOT NULL,
	[MLOANV] [numeric](15,2) NOT NULL,
	[MBYPWR] [numeric](15,2) NOT NULL,
	[MPNDIV] [numeric](15,2) NOT NULL,
	[MPNINT] [numeric](15,2) NOT NULL,
	[MLQVAL] [numeric](15,2) NOT NULL,
	[MMRGVL] [numeric](15,2) NOT NULL,
	[MOTECR] [numeric](15,2) NOT NULL,
	[MOTEDR] [numeric](15,2) NOT NULL,
	[MPREM] [numeric](15,2) NOT NULL,
	[MOOTEC] [numeric](15,2) NOT NULL,
	[MAVSOD] [numeric](15,2) NOT NULL,
	[MLOPRM] [numeric](15,2) NOT NULL,
	[MUNUPL] [numeric](15,2) NOT NULL,
	[MAVGME] [numeric](15,2) NOT NULL,
	[MJPIR] [numeric](15,2) NOT NULL,
	[MJPIRC] [numeric](15,2) NOT NULL,
	[MJPMR] [numeric](15,2) NOT NULL,
	[MJPRT2] [numeric](15,2) NOT NULL,
	[MTAR] [numeric](15,2) NOT NULL,
	[MEPOTE] [numeric](15,2) NOT NULL,
	[MLVUST] [numeric](15,2) NOT NULL,
	[MTE] [numeric](15,2) NOT NULL,
	[MAVGBL] [numeric](15,2) NOT NULL,
	[MAVGOV] [numeric](15,2) NOT NULL,
	[MCVTAB] [numeric](15,8) NOT NULL,
	[MCMACR] [numeric](15,2) NOT NULL,
	[MCMACU] [numeric](15,2) NOT NULL,
	[MSPNOV] [numeric](15,2) NOT NULL,
	[MEEXM] [numeric](15,2) NOT NULL,
	[MEIRT] [numeric](15,2) NOT NULL,
	[MEOIR] [numeric](15,2) NOT NULL,
	[MEOMR] [numeric](15,2) NOT NULL,
	[MFEXMR] [numeric](15,2) NOT NULL,
	[MGEUDC] [numeric](15,2) NOT NULL,
	[MNCOTE] [numeric](15,2) NOT NULL,
	[MCCDNT] [numeric](15,2) NOT NULL,
	[MEQPCT] [numeric](15,2) NOT NULL,
	[MREGCV] [numeric](15,2) NOT NULL,
	[MCVTAF] [numeric](15,8) NOT NULL,
	[MTDVAL] [numeric](15,2) NOT NULL,
	[MTCC] [numeric](15,2) NOT NULL,
	[MMRGLM] [numeric](15,2) NOT NULL,
	[MPNOTH] [numeric](15,2) NOT NULL,
	[MIRCIC] [numeric](15,2) NOT NULL,
	[MIRCEC] [numeric](15,2) NOT NULL,
	[MDEFOT] [numeric](15,2) NOT NULL,
	[MSECAM] [numeric](15,2) NOT NULL,
	[MCLMGN] [numeric](15,2) NOT NULL,
	[MCLOTE] [numeric](15,2) NOT NULL,
	[MSPNAE] [numeric](15,2) NOT NULL,
	[MMVUCI] [numeric](15,2) NOT NULL,
	[MACRET] [numeric](15,2) NOT NULL,
	[MPOOTE] [numeric](15,2) NOT NULL,
	[MUNDEP] [numeric](15,2) NOT NULL,
	[MPRTC] [numeric](15,2) NOT NULL,
	[MPRSMA] [numeric](15,2) NOT NULL,
	[MLVTM4] [numeric](15,2) NOT NULL,
	[MLVTM3] [numeric](15,2) NOT NULL,
	[MLVTM2] [numeric](15,2) NOT NULL,
	[MPREOI] [numeric](15,2) NOT NULL,
	[MPREIR] [numeric](15,2) NOT NULL,
	[MPRFXM] [numeric](15,2) NOT NULL,
	[MPRFXI] [numeric](15,2) NOT NULL,
	[MPRFIR] [numeric](15,2) NOT NULL,
	[MPROTE] [numeric](15,2) NOT NULL,
	[MPRTE] [numeric](15,2) NOT NULL,
	[MPRLQV] [numeric](15,2) NOT NULL,
	[MPRRCV] [numeric](15,2) NOT NULL,
	[MPRBAL] [numeric](15,2) NOT NULL,
	[MBNRY1] [varchar](1) NOT NULL,
	[MBNRY2] [varchar](1) NOT NULL,
	[MBNRY3] [varchar](1) NOT NULL,
	[MBNRY4] [varchar](1) NOT NULL,
	[MBNRY5] [varchar](1) NOT NULL,
	[MMISC1] [varchar](1) NOT NULL,
	[MMISC2] [varchar](1) NOT NULL,
	[MMISC3] [varchar](1) NOT NULL,
	[MMISC4] [varchar](1) NOT NULL,
	[MMISC5] [varchar](1) NOT NULL,
	[MMISC6] [varchar](1) NOT NULL,
	[MMISC7] [varchar](1) NOT NULL,
	[MMISC8] [varchar](1) NOT NULL,
	[MMISC9] [varchar](1) NOT NULL,
	[MMISC0] [varchar](1) NOT NULL,
	[MCND01] [varchar](1) NOT NULL,
	[MCND02] [varchar](1) NOT NULL,
	[MCND03] [varchar](1) NOT NULL,
	[MCND04] [varchar](1) NOT NULL,
	[MCND05] [varchar](1) NOT NULL,
	[MCND06] [varchar](1) NOT NULL,
	[MCND07] [varchar](1) NOT NULL,
	[MCND08] [varchar](1) NOT NULL,
	[MCND09] [varchar](1) NOT NULL,
	[MCND10] [varchar](1) NOT NULL,
	[MUSFL1] [varchar](1) NOT NULL,
	[MUSFL2] [varchar](1) NOT NULL,
	[MUSFL3] [varchar](1) NOT NULL,
	[MUSFL4] [varchar](1) NOT NULL,
	[MUSFL5] [varchar](1) NOT NULL,
	[MUSFL6] [varchar](1) NOT NULL,
	[MUSFL7] [varchar](1) NOT NULL,
	[MUSFL8] [varchar](1) NOT NULL,
	[MUSFL9] [varchar](1) NOT NULL,
	[MUSFLA] [varchar](1) NOT NULL,
	[MUKFL1] [varchar](1) NOT NULL,
	[MUKFL2] [varchar](1) NOT NULL,
	[MUKFL3] [varchar](2) NOT NULL,
	[MUKFL4] [varchar](1) NOT NULL,
	[MFRFL1] [varchar](1) NOT NULL,
	[MFRFL2] [varchar](1) NOT NULL,
	[MFRFL3] [varchar](1) NOT NULL,
	[MJPFL1] [varchar](1) NOT NULL,
	[MJPFL2] [varchar](1) NOT NULL,
	[MJPFL3] [varchar](1) NOT NULL,
	[MHKFL1] [varchar](1) NOT NULL,
	[MGEFL1] [varchar](1) NOT NULL,
	[MITFL1] [varchar](1) NOT NULL,
	[DateLoaded] [datetime] NOT NULL,
	[DateLoaded_Local] [datetime] NOT NULL DEFAULT GETDATE()
	
) ON [PRIMARY]
GO

SET ANSI_PADDING OFF
GO