	[PRECID] [varchar](255) NOT NULL DEFAULT '',
	[PFIRM] [varchar](255) NOT NULL DEFAULT '',
	[POFFIC] [varchar](255) NOT NULL DEFAULT '',
	[PACCT] [varchar](255) NOT NULL DEFAULT '',
	[PATYPE] [varchar](255) NOT NULL DEFAULT '',
	[PCUSIP] [varchar](255) NOT NULL DEFAULT '',
	[PCUSP2] [varchar](255) NOT NULL DEFAULT '', 
	[PCTYM] [varchar](255) NOT NULL DEFAULT '',
	[PSBCUS] [varchar](255) NOT NULL DEFAULT '',
	[PSTYPE] [varchar](255) NOT NULL DEFAULT '',
	[PSUBTY] [varchar](255) NOT NULL DEFAULT '',
	[PSTYP2] [varchar](255) NOT NULL DEFAULT '',
	[PSTRIK] [varchar](255) NOT NULL DEFAULT '',
	[PEXPDT] [varchar](255) NOT NULL DEFAULT '',
	[PSUBAC] [varchar](255) NOT NULL DEFAULT '',
	[PDEAL] [varchar](255) NOT NULL DEFAULT '',
	[PTDATE] [varchar](255) NOT NULL DEFAULT '',       
	[PTPRICPPPBPPTRACE    PICPREFNO      PSWAC1      PPPSWAC2      PPPPAPPPRR  PRIPPSNAME              PSRCAC    PREPREFRPPOFPOFFAPOPMPPPPPPPPPPPPPPPPPPPP             PQTYPPRTQ                     PBUSTQ           PMAKEQ           PLEAVQ            PSEGQ            PTFRQ           PDLVYQ           PDLVYAPSDPSDSC1                        PSDSC2                        PSDSC3                        PTDPTDSC1                        PTDSC2                        PTDSC3                                   PMKVAL           PYSTMV           PMULTF     PSDATE           PEXRAT     PRXDAT       PIAD     PYIELD           PDCTCO PDELTA     PLTDATPCTLNO    PPPEPFPPSYMBLPPPT     PMATDTPPRTPR          PBASIS           PCLOSE     PPRCDTPPRTCP                PUNDCPPPRTUC                PPRVCP           PTRPRCPEXPR  PPRICE      PPPCUPCPPCPCPCPLPPPSPPPUCUSP                 PCVTBLPEXBKPOPBKPOPFRPGPGIVFPIPIEFRPCARPORDER                   PCHIT          PPPPORPOPTIME PTPPSPPBPBPBPBPBP           PMINIT           PMVARN     PMUNTL           PMGNCVPPREPREL1PPPREPREL2PPPREPREL3P            PCOMM            PFEE1            PFEE2            PFEE3            PFEE4            PFEE5            PFEE6            PFEE7            PFEE8            PFEE9           PGICHG           PBKCHG           POTHER           PGROSS             PNET           PMBKOF           PMFLOR           PMORDR           PMWIRE           PMOTHRPAPAPAPAPAPAPAPAPAPAPAPAPAPAPAPAPAPAPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP            POVNQ            PDAYQ            PSCRQ            PSPDQ            POVNC            PDAYC            PSCRC            PSPDCPSORTK                                            PLEPBA   PRECNOPCLRID    PPIPFBACPPPSPPPSPUSER     PWSID        PWSTIMPP   PXTRCT            PBQTY            PSQTYP            PAMT1P            PAMT2PPPPCUPCUPC