USE [GMIDATA]
GO

DROP TABLE [dbo].[WFUTM]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[WFUTM](
	[GMIEX] [varchar](255) NOT NULL DEFAULT '',
	[EXCHDESC] [varchar](255) NOT NULL DEFAULT '',
	[GMIFC] [varchar](255) NOT NULL DEFAULT '',
	[TYPE] [varchar](255) NOT NULL DEFAULT '',
	[PRODTYP] [varchar](255) NOT NULL DEFAULT '', --5
	[PROMPT] [varchar](255) NOT NULL DEFAULT '',
	[DESC] [varchar](255) NOT NULL DEFAULT '',
	[LONGDESC] [varchar](255) NOT NULL DEFAULT '',
	[EXALTFC] [varchar](255) NOT NULL DEFAULT '',
	[OTHERDESC] [varchar](255) NOT NULL DEFAULT '', --10
	[EXPCOMM] [varchar](255) NOT NULL DEFAULT '',
	[SPANCOMM] [varchar](255) NOT NULL DEFAULT '',
	[CFTCFC] [varchar](255) NOT NULL DEFAULT '', --13
	[DateLoaded] [datetime] NOT NULL DEFAULT GETDATE()
	
	--CONSTRAINT [PK_WFUTM] PRIMARY KEY CLUSTERED
	--(
	--	[Field_1] ASC,
	--	[Field_2] ASC,
	--	[Field_3] ASC
	--)
) ON [PRIMARY]
GO

SET ANSI_PADDING OFF
GO