USE master
GO

SET NOCOUNT ON

ALTER DATABASE GMIDATA
    MODIFY FILE (NAME = 'GMIDATA_log', FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\GMIDATA_log.ldf');

SET NOCOUNT OFF